### ISSUE TITLE
为什么docker启动单机版polaris，其他机器无法访问呢？

### ISSUE THREAD

**Issue by taolive** [polarismesh/polaris#1023]
**Describe the bug**
在A机器（防火墙已经开放8080等端口）上使用docker-compose启动，其他机器浏览器无法访问8080端口
```yaml
services:
  polaris:
    image: polarismesh/polaris-server-standalone:v1.12.0
    container_name: polaris
    restart: always
    network_mode: "host"
    privileged: true
    hostname: polaris-standatone
    expose:
      - 15010:15010
      - 8101:8101
      - 8100:8100
      - 8080:8080
      - 8090:8090
      - 8091:8091
      - 8093:8093
      - 8761:8761
      - 9000:9000
      - 9090:9090
```
以上是`docker-compose.yml`文件配置

使用docker-compose 命令查看
```shell
[root@CentOS9 a]# docker-compose ps
NAME                IMAGE                                           COMMAND              SERVICE             CREATED             STATUS              PORTS
polaris             polarismesh/polaris-server-standalone:v1.12.0   "/bin/bash run.sh"   polaris             3 seconds ago       Up 2 seconds
[root@CentOS9 a]# docker logs -f polaris
prepare install polaris standalone...
polaris-console listen port info
console_port=8080

polaris-server listen port info
eureka_port=8761
xdsv3_port=15010
prometheus_sd_port=9000
service_grpc_port=8091
config_grpc_port=8093
api_http_port=8090

polaris-limiter-server listen port info
polaris_limiter_http_port=8100
polaris_limiter_grpc_port=8101

prometheus-server listen port info
prometheus_server_port=9090

pushgateway-server listen port info
pushgateway_server_port=
```

防火墙：
``` shell
[root@CentOS9 a]# firewall-cmd --permanent --zone=public --query-port=8080/tcp  --query-port=8091/tcp --query-port=8090/tcp
8080/tcp: yes
8091/tcp: yes
8090/tcp: yes
```

查看本地端口
```shell
[root@CentOS9 a]# telnet localhost 8080
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
```

**Environment**
- Version: [v1.12.0]
- OS: [CentOS8]
- 客户机：macOS，浏览器：edge
