### ISSUE TITLE
polaris-server 本机IP信息获取和预期不对

### ISSUE THREAD

**Issue by Ive4** [polarismesh/polaris#1089]
**Describe the bug**
访问curl "http://192.168.0.104:8090/prometheus/v1/clients"
返回结果为：
[
 {
  "targets": [
   "127.0.0.1:8090"
  ],
  "labels": {
   "__meta_polaris_client_id": "c34d52e1474f4e8463ebcc3cec1a57bb9f9eac2a",
   "__metrics_path__": "/metrics",
   "__scheme__": "http"
  }
 }
]⏎ 

期望结果为192.168.0.104
**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: v1.16.1
- OS: CentOS6

**Additional context**

**Comment by chuntaojun** [comment]
单机版？还是集群版，如果没有这是 probe_address，默认地址就是127.0.0.1

**Comment by chuntaojun** [comment]
```yaml
  # Register as Arctic Star Service
  polaris_service:
    # probe_address: ##DB_ADDR##
    enable_register: true
    isolated: false
    services:
      - name: polaris.checker
        protocols:
          - service-grpc
```
