### ISSUE TITLE
网关接入失败

### ISSUE THREAD

**Issue by karl-chanel** [polarismesh/polaris#1129]
**Describe the bug**
nginx和envoy网关根据文档操作无法接入
**To Reproduce**
Steps to reproduce the behavior.
使用的是docker部署的standalone最新版本的polaris
**Expected behavior**
我通过在k8中部署官方提供的nginx-gateway和在vm上直接部署都无法接入
**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]
ubuntu22.4
**Additional context**

**Comment by chuntaojun** [comment]
具体不能接入的表现是什么？

**Comment by karl-chanel** [comment]
还没睡呀，我在测在弄，看一下最后能不能好，要是不行的话，再把详细信息填上来

**Comment by chuntaojun** [comment]
可以具体描述下，envoy的话，envoy_gateway 目前只支持了路由能力，限流能力以及熔断暂时未接入

**Comment by karl-chanel** [comment]
我的polaris没有跑k8中，我是docker部署的standalone版本，我先试的用nginx做网关，在vm上直接部署和在k8上部署都不行，然后试了下envoy,我对envoy不熟，就按你们的文档来的，无法通过xds获取到配置的规则polaris也没有显示envoy有注册上去

**Comment by chuntaojun** [comment]
1. envoy_gateway 是不注册的，需要用户自己创建 envoy_gateway 对应的服务信息

**Comment by karl-chanel** [comment]
我在polaris控制台注册了服务名，没有填实例信息

**Comment by chuntaojun** [comment]
> 我在polaris控制台注册了服务名，没有填实例信息

那这一步做了就可以了，剩下的就是看 envoy 是否成功连接到北极星 xds-server

**Comment by karl-chanel** [comment]
node:
  2   id: "gateway~default/c962adc3-673e-4637-9ba8-969d755ef66a~127.0.0.1"
  3   cluster: "CLUSTER_NAME"
  4   metadata:
  5     gateway_service: envoy_gateway
  6     gateway_namespace: default
  7
  8 dynamic_resources:
  9   lds_config:
 10     ads: {}
 11     resource_api_version: V3
 12   cds_config:
 13     ads: {}
 14     resource_api_version: V3
 15   ads_config:
 16     api_type: GRPC
 17     transport_api_version: V3
 18     grpc_services:
 19       - google_grpc:
 20         target_uri: 192.168.0.229:15010
 21           stat_prefix: polarismesh
 22           channel_args:
 23             args:
 24               grpc.http2.max_ping_strikes:
 25                 int_value: 0
 26               grpc.keepalive_time_ms:
 27                 int_value: 10000
 28               grpc.keepalive_timeout_ms:
 29                 int_value: 20000
 30
 31 admin:
 32   access_log_path: /dev/stdout
 33   address:
 34     socket_address:
 35       address: 0.0.0.0
 36       port_value: 15000

**Comment by karl-chanel** [comment]
<img width="1280" alt="屏幕截图 2023-05-17 002631" src="https://github.com/polarismesh/polaris/assets/78248702/996bc2d6-f718-4bc6-9bde-b9d209eed1bf">

**Comment by chuntaojun** [comment]
你的 envoy 也是容器？

**Comment by karl-chanel** [comment]
对，可以的192.168.0.229是我的eth0 ,我没直接用公网地址，刚才是在另一台机器测得有问题，上面的配置文件是刚从你的回答里copy的，但现在提示yml格式错误，

**Comment by chuntaojun** [comment]
```
node:
  id: "default/c962adc3-673e-4637-9ba8-969d755ef66a~127.0.0.1"
  cluster: "CLUSTER_NAME"

dynamic_resources:
  lds_config:
    ads: {}
    resource_api_version: V3
  cds_config:
    ads: {}
    resource_api_version: V3
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - google_grpc:
          target_uri: {SERVER_IP}:15010
          stat_prefix: polarismesh
          channel_args:
            args:
              grpc.http2.max_ping_strikes:
                int_value: 0
              grpc.keepalive_time_ms:
                int_value: 10000
              grpc.keepalive_timeout_ms:
                int_value: 20000

admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000
```
