### ISSUE TITLE
polaris.checker 在运行一段时间后实例状态变为不健康

### ISSUE THREAD

**Issue by pemako** [polarismesh/polaris#1189]
**Describe the bug**
polaris-server 部署了两个实例节点，前端是nginx做的负载均衡，服务正常启动后两个实例节点都是健康的。在运行了一段时间后发现其中的一个实例节点变为异常状态，实际该节点是正常的。

截图及配置信息如下

<img width="1625" alt="image" src="https://github.com/polarismesh/polaris/assets/7908831/d794a352-2b43-4472-b4ae-134b348912ed">

```yaml
bootstrap:
  polaris_service:
    probe_address: xxxx 
...

healthcheck:
  open: true
  service: polaris.checker
  slotNum: 30
  minCheckInterval: 1s
cycle
  maxCheckInterval: 30s
  clientReportInterval: 120s
  batch:
    heartbeat:
      open: true
      queueSize: 10240
      waitTime: 32ms
      maxBatchCount: 32
      concurrency: 64
  checkers:
    - name: heartbeatLeader 
 ```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: v1.17.2
- OS: centos7.6.1810

**Additional context**
