### ISSUE TITLE
Logs are printed to different log files based on the type

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#119]
**What is the feature you want to add?**

Logs are printed to different log files based on the type

example：
if log about healthcheck, may be should print to the polaris-health-check.log
if log about storage, may be should print to the polaris-store.log

**Why do you want to add this feature?**

When polaris-server runs for a long time, a large number of logs will be generated. If various types of logs are output to the same log file, it may be troublesome to troubleshoot the problem. If you divide the log output file according to the category, locate the problem or It is more convenient to do something based on the log

**How to implement this feature?**

**Additional context**

**Comment by DHBin** [comment]
我的解决方案是：

根据配置不同的包路径写入到不同的log文件中。

```yaml
bootstrap:
  # 全局日志
  logger:
    OutputPath:
      naming: log/polaris-naming.log
      healthcheck: log/polaris-health-check.log
      store: log/polaris-store.log
    DefalutOutputPath: log/polaris-server.log
```

- 如果是多层级的包路径，考虑使用包路径的前缀匹配。
- 在构建zapcore.Core的时候，对log文件路径去重合并，即比如上面的`naming`、`healthcheck`都指向`log/polaris.log`就只创建一个zapcore.Core，两个路径指向同一个zapcore.Core

最终在`patchTable.write`函数匹配不同的Core写日志，如果匹配不上默认输出。


-----
机翻：
My solution is to write to different log files according to the configuration of different package paths. 


```yaml
bootstrap:
  # 全局日志
  logger:
    OutputPath:
      naming: log/polaris-naming.log
      healthcheck: log/polaris-health-check.log
      store: log/polaris-store.log
    DefalutOutputPath: log/polaris-server.log
```

- If it is a multi-level package path, consider using the prefix matching of the package path
- when construct zap.Core will de-duplicate log file path. such as the above package path `naming` and `healthcheck` all point to `log/polaris.log`,  those two paths point to the same object

finally,match different cores to write logs in `patchTable.write` function, if it doesn't match, it will output by default core.
