### ISSUE TITLE
单机部署版本如何部署 polaris.discover  ？

### ISSUE THREAD

**Issue by coder2z** [polarismesh/polaris#1409]
单机部署版本如何部署 polaris.discover  ？

https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%AE%89%E8%A3%85/%E5%8D%95%E6%9C%BA%E7%89%88%E5%AE%89%E8%A3%85/

我们这边想在docker 中最小启动北极星，但是希望能有北极星的全部功能包括：服务注册 服务发现。

这个不会用于生产，只是在本地或者流水线上能验证一些能力。

**Comment by chuntaojun** [comment]
```yaml
  # Register as Arctic Star Service
  polaris_service:
    ## level: self_address > network_inter > probe_address
    ## Obtain the IP of the VM or POD where Polaris is located by making a TCP connection with the probe_adreess address
    # probe_address: ##DB_ADDR##
    ## Set the name of the gateway to get your own IP
    # network_inter: eth0
    ## Show the setting node itself IP information
    # self_address: 127.0.0.1
    # disable_heartbeat disable polaris_server node run heartbeat action to keep lease polaris_service
    # disable_heartbeat: true
    # Whether to open the server to register
    enable_register: true
    # Registered North Star Server Examples isolation status
    isolated: false
    # Service information that needs to be registered
    services:
      # service name
      - name: polaris.checker
        # Set the port protocol information that requires registration
        protocols:
          - service-grpc
      - name: polaris.discover
        # Set the port protocol information that requires registration
        protocols:
          - service-grpc
```
