### ISSUE TITLE
[Discuss] redis 开放给用户自定调整参数列表

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris#417]
**What is the feature you want to add?**

redis 组件目前开放出了全部的参数供用户调整，是否有必要开放出这么多的参数，还是只开放部分参数

**Why do you want to add this feature?**

**How to implement this feature?**

**Additional context**

**Comment by chuntaojun** [comment]
https://github.com/polarismesh/polaris/issues/415

**Comment by magederek** [comment]
#### v1.9版本存在的参数
```yaml
  checkers:
    - name: heartbeatRedis
      option:
        kvAddr: 127.0.0.1:6739 # redis地址
        kvUser: admin # 开启ACL时的username
        kvPasswd: admin # 开启ACL时的password或未开启ACL时的auth
        poolSize: 200 # 链接池大小
        minIdleConns: 30 # 最小空闲链接数量
        idleTimeout: 120s # 空闲超时时间
        connectTimeout: 200ms # 连接超时时间
        msgTimeout: 200ms # 读写超时时间
        concurrency: 200 # 客户端并发读写数量
        compatible: false # 是否开启兼容模式
        maxRetry: 2 # 失败最大重试次数
        minBatchCount: 10 # 最小触发批量处理的任务数量
        waitTime: 50ms # 定时触发任务处理的间隔
        withTLS: false # 是否启用TLS
``` 

#### main分支下新增的参数
- [ ] maxRetries: 看起来跟已有的maxRetry是同一个内容，建议可以不需要新增这个参数
- [x] DB: 允许用户选择redis的DB，建议修改为**小写db**
- [ ] readTimeout: 读超时，当前的msgTimeout的配置最终会反应到这个配置中，建议无需增加，沿用msgTimeout即可
- [ ] writeTimeout: 写超时，当前的msgTimeout的配置最终会反应到这个配置中，建议无需增加，沿用msgTimeout即可
- [ ] poolTimeout: 从连接池获取链接的等待超时，默认为读超时+1秒，建议无需暴露
- [x] maxConnAge: 连接最长的使用时间，一般用于使用域名链接redis时定期进行域名重解析，使负载更为均衡，建议可以保留
- [ ] tlsConfig: 当前这个配置未加json tag，无法生效。对于当前场景，设置withTLS后，即可开启server的TLS证书认证，对于不使用mTLS的场景，withTLS已足够，建议如后续需要支持mTLS时再对tlsConfig进行有限度的支持。

#### 更多参数
考虑到redis客户端可以使用多种模式，如sentinel、failover、cluster等，可以抽取各个模式均具有的参数作为顶层option，对于不同模式独有的参数，封装到具体的子配置中
