### ISSUE TITLE
由于polaris-server.yaml配置不当，引起polaris-server服务启动之后访问不了

### ISSUE THREAD

**Issue by XW512** [polarismesh/polaris#560]
在修改  polaris-server.yaml配置文件中，忘记注释掉   
###单机文件存储插件
  #name: boltdbStore
的配置，开启了数据库存储插件的配置：
###存储配置
store:
###数据库存储插件
  name: defaultStore
  option:
    master:
      dbType: mysql
      dbName: polaris_server
      dbAddr: 数据库地址，格式为ip:port
      dbUser: 数据库用户名
      dbPwd: 数据库密码
导致 polaris-server 启动之后，访问不了，希望这里能对store进行区分配置单机文件存储插件和数据库存储插件的配置，感谢感谢

**Comment by chuntaojun** [comment]
这里北极星服务端需要针对一些插件是否互斥做启动检查，如果插件之间是互斥的，如果配置不对，那么启动时应该报错

**Comment by GuiyangZhao** [comment]
我试了以下配置都能正常加载并启动:

1. name: boltdbStore,但却用的是mysql的配置, 能正常启动,并运行, 此时程序表现是用的boltdbStore, polaris.bolt, path 用的是默认值
```
store:
  # 单机文件存储插件
  name: boltdbStore
#  option:
#    path: ./polaris.bolt
  # 数据库存储插件
#  name: defaultStore
  option:
    master:
      dbType: mysql
      dbUser: user
      dbPwd: password
      dbAddr: 127.0.0.1:3306
      dbName: polaris_server
      maxOpenConns: 300
      maxIdleConns: 50
      connMaxLifetime: 300 # 单位秒
      txIsolationLevel: 2 #LevelReadCommitted
```
2. 两个插件共存, 能正常起来并运行, 此时程序表现是用defaultStore,以及其配置
```
store:
  # 单机文件存储插件
  name: boltdbStore
  option:
    path: ./polaris.bolt
  # 数据库存储插件
  name: defaultStore
  option:
    master:
      dbType: mysql
      dbUser: user
      dbPwd: password
      dbAddr: 127.0.0.1:3306
      dbName: polaris_server
      maxOpenConns: 300
      maxIdleConns: 50
      connMaxLifetime: 300 # 单位秒
      txIsolationLevel: 2 #LevelReadCommitted
```

@XW512 方便提供下你那边错误的配置吗? thx.

**Comment by chuntaojun** [comment]
他是这样子的 

```yaml
store:
  # 单机文件存储插件
  name: boltdbStore
  # 数据库存储插件
  name: defaultStore
  option:
    master:
      dbType: mysql
      dbUser: user
      dbPwd: password
      dbAddr: 127.0.0.1:3306
      dbName: polaris_server
      maxOpenConns: 300
      maxIdleConns: 50
      connMaxLifetime: 300 # 单位秒
      txIsolationLevel: 2 #LevelReadCommitted
```
