### ISSUE TITLE
polaris-cleanup 中的 DeleteUnHealthyInstance 功能集成到 polaris-server

### ISSUE THREAD

**Issue by shichaoyuan** [polarismesh/polaris#922]
polaris-cleanup 中的 DeleteUnHealthyInstance 功能集成到 polaris-server

**Comment by shichaoyuan** [comment]
在 yaml 配置文件中增加
```yaml
# Maintain configuration
maintain:
  jobs:
    # Clean up long term unhealthy instance
    - name: DeleteUnHealthyInstance
      option:
        cronSpec: "0 0 2 * * ?"
        instanceDeleteTimeout: 60m
    # Delete auto-created service without an instance
    - name: DeleteEmptyAutoCreatedService
      option:
        cronSpec: "0 0 * * * *"
```
