### ISSUE TITLE
使用envoy作为API网关，接入polaris的问题

### ISSUE THREAD

**Issue by lei32323** [polarismesh/polaris#985]
## 问题？

参考 [blue-green-releasing](https://github.com/polarismesh/examples/blob/main/grayreleasing/envoyproxy/blue-green-releasing/k8s/02-envoy-bootstrap-config.yaml)  使用envoy作为API网关，以xds的方式接入polaris，envoy无法获取polaris中的lds和cds数据

## 版本
+ envoy:  1.23.1 
+ polaris server:  1.13.6

## 前置
+ polaris server 已开启xds-v3 ,端口号：15010

## 相关配置
+ envoy.yaml
``` yaml 
node:
  id: blue-green/60c543b9-df2e-4610-b057-2fef16a973bd~10.0.5.52
  cluster: envoy-cluster
dynamic_resources:
  lds_config:
    resource_api_version: V3
    path_config_source:
      path: lds.yaml
  cds_config:
    resource_api_version: V3
    path_config_source:
      path: cds.yaml
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
    - google_grpc:
        target_uri: "127.0.0.1:15010"
        stat_prefix: polarismesh
        channel_args:
          args:
            grpc.http2.max_pings_without_data:
              int_value: 1
            grpc.keepalive_time_ms:
              int_value: 10000
            grpc.keepalive_timeout_ms:
              int_value: 20000
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902
```

+ lds.yaml

```yaml
resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_15001
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: http
          http_filters:
          - name: envoy.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:              
              - match:
                  prefix: "/"
                route:
                  weighted_clusters:
                    total_weight: 100
                    clusters:
                    - name: user
                      weight: 80
                      metadata_match:
                        filter_metadata:
                          envoy.lb:
                            version: 1.0.0
                    - name: user
                      weight: 20
                      request_headers_to_add:
                      - header:
                          key: gray
                          value: "true"
                      metadata_match:
                        filter_metadata:
                          envoy.lb:
                            version: 2.0.0
```

+ cds.yaml
```yaml
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: user
    type: EDS
    eds_cluster_config:
      service_name: user
      eds_config:
        ads: {}
        resource_api_version: V3
    connect_timeout: 5s
    lb_subset_config:
      fallback_policy: ANY_ENDPOINT
      subset_selectors:
      - keys:
        - version
        fallback_policy: NO_FALLBACK
```

## envoy信息
+ stats
```text
cluster.user.init_fetch_timeout: 1
cluster_manager.cds.init_fetch_timeout: 0
listener_manager.lds.init_fetch_timeout: 0
```

+ cluster
```text
user::observability_name::user
user::default_priority::max_connections::1024
user::default_priority::max_pending_requests::1024
user::default_priority::max_requests::1024
user::default_priority::max_retries::3
user::high_priority::max_connections::1024
user::high_priority::max_pending_requests::1024
user::high_priority::max_requests::1024
user::high_priority::max_retries::3
user::added_via_api::true
user::eds_service_name::user
```
+ dump_config 
[dump_config.txt](https://github.com/polarismesh/polaris/files/10894046/dump_config.txt)

## 日志
+ envoy 启动日志
[envoy启动日志.txt](https://github.com/polarismesh/polaris/files/10894050/envoy.txt)

+ polaris-xdsv3日志
[polaris-xdsv3.txt](https://github.com/polarismesh/polaris/files/10894059/polaris-xdsv3.txt)
