### ISSUE TITLE
not check password at mysql config.

### ISSUE THREAD

**Issue by horizonzy** [polarismesh/polaris#99]
**Describe the bug**
mysql password is not force required. my local mysql password is null.

```
 mac@apples-MacBook-Pro ~ mysql -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1024
Server version: 8.0.26 Homebrew

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

So I config mysql like this:
```
  name: defaultStore
  option:
    master:
      dbType: mysql
      dbUser: root
      dbPwd:
      dbAddr: 127.0.0.1
      dbName: polaris_server
      maxOpenConns: -1
      maxIdleConns: -1
      connMaxLifetime: 300 # 单位秒
      txIsolationLevel: 2 #LevelReadCommitted
```

err log:
```
err: Config Plugin defaultStore missing database param
```
